name: gradproj
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.8.0
  cloud_firestore: ^4.10.0
  # firebase_auth: ^4.7.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_spinkit: ^5.1.0
  crypto: ^3.0.0
  flutter_riverpod: ^2.6.1
  material_floating_search_bar_2: ^0.5.0
  line_awesome_flutter: ^3.0.1
  supabase_flutter: ^2.8.2
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  file_picker: ^8.1.6
  permission_handler: ^11.1.0
  multi_image_picker_plus: ^0.0.6
  image_picker: ^0.8.7+4
  photo_manager: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_email_sender: ^6.0.3
  mailer: ^6.4.1
  google_sign_in: ^6.2.2
  dart_jsonwebtoken: ^2.14.2
  jwt_decoder: ^2.0.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/facebook.jpg
    - images/google.jpg
    - images/background.jpg
    - images/listingPlaceholder.jpg
    - images/keyimage.jpg
    - images/google-logo.png

